[package]
name = "stoat_gui"
version = "0.1.0"
edition = "2021"
description = "Iced-based GUI for the Stoat text editor"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"


[lints]
workspace = true

[dependencies]
# Core editor logic
stoat = { path = "../stoat" }
tokio = { workspace = true, features = ["fs", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
