[package]
name = "stoat_gui"
version = "0.1.0"
edition = "2021"
description = "GUI for the Stoat text editor using GPUI"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"

[lib]
path = "src/stoat_gui.rs"

[lints]
workspace = true

[dependencies]
stoat = { path = "../stoat" }
stoat_rope_v3 = { path = "../rope_v3" }
gpui = { git = "https://github.com/zed-industries/zed.git" }
text = { git = "https://github.com/zed-industries/zed.git" }
anyhow = "1.0"
